apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: token-example
commonLabels:
  app.kubernetes.io/instance: token-example
resources:
  - namespace.yaml
bases:
  - ClientApp
  - ServerApp
