apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: server
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
configMapGenerator:
  - name: server
    files:
      - ServerApp.csproj
      - Program.cs
      - appsettings.json
