apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: client
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
configMapGenerator:
  - name: client
    files:
      - ClientApp.csproj
      - Program.cs
      - appsettings.json
